name: Static Code Analysis with PMD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pmd-analysis:
    name: Run PMD Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run PMD Analysis
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'java-basic'
        analyze_modified_files_only: false
        fail_on_violations: true # This makes the workflow fail if PMD reports violations

    - name: Upload PMD Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: PMD-Report
        path: pmd-report.xml
