name: Static Code Analysis with PMD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  pmd-analysis:
    name: Run PMD Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Run PMD Analysis
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'category/java/bestpractices.xml'
        analyzeModifiedFilesOnly: false
        createGitHubAnnotations: true
    - name: Upload PMD Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: PMD-Report
        path: pmd-report.sarif